### PR TITLE
FDBT-1303 | Fix for issue with API calls

### PR DESCRIPTION
**Pull request by joyalseb**
https://cogcloud.atlassian.net/browse/FDBT-1303

### CODE REVIEW

**Comment by SPrasadT** [comment]
@joyalseb Should this binary be release under 1.8.8 or 1.8.9 version. Please confirm

**Comment by joyalseb** [comment]
> @joyalseb Should this binary be released under 1.8.8 or 1.8.9 version. Please confirm

It should be under 1.8.8 since that version won't work with this fix

**Comment by SPrasadT** [comment]
> > @joyalseb Should this binary be released under 1.8.8 or 1.8.9 version. Please confirm
> 
> It should be under 1.8.8 since that version won't work with this fix

Then we will have to delete the existing 1.8.8 release and create a new one on the same version. Let me do that.

**Review by SPrasadT — APPROVED** [review]
Approved by the release team.

**Comment by joyalseb** [comment]
> > > @joyalseb Should this binary be released under 1.8.8 or 1.8.9 version. Please confirm
> > 
> > 
> > It should be under 1.8.8 since that version won't work with this fix
> 
> Then we will have to delete the existing 1.8.8 release and create a new one on the same version. Let me do that.

Ok, thanks, Sai

**Comment by SPrasadT** [comment]
@joyalseb check the releases page. Thanks.

**Pull request merged**
