### PR TITLE
Added dynamic exploration name code changes

### PR DESCRIPTION
**Pull request by BhavanaR28**
Added dynamic exploration name code changes, ticket id: INT-86

### CODE REVIEW

**Comment by BhavanaR28** [comment]
Screenshot (120)
Screenshot (121)

**Review by SPrasadT — CHANGES_REQUESTED** [review]
@BhavanaR28 @GorlaS4 - Please update the readme on usage of these functionalities.

**Comment by BhavanaR28** [comment]
updated commands for api service also!
________________________________

**Review by SPrasadT — APPROVED** [review]
Changes looks good.

**Pull request merged**
